#!/bin/bash -e
# This gets passed with each submission to tmc-sandbox

# This gets run under 'su', so we want to source profile mostly to get any special PATH.
# Sourcing seems to terminate the script with -e, even when the return status is 0.
# I have absolutely no idea why. We work around it with the '|| true'.
#. /etc/profile || true

# Source user params if any.
# Though the variable names and content format here are limited,
# the contents should be treated carefully, despite us being in a sandbox.
#
# Included variables: error_msg_locale
#
if [ -r .tmcparams ]; then
  . ./.tmcparams
fi

echo "User id: $(id)"

if [ -z "$error_msg_locale" ]; then
  echo "Setting error_msg_locale"
  error_msg_locale=en
fi

# Source .tmcrc if any
if [ -f .tmcrc ]; then
  echo "Including .tmcrc"
  . ./.tmcrc
fi

if [ -e /tmc-langs.jar ]; then
  echo "Copying tmc-langs.jar from the image"
  cp /tmc-langs.jar tmc-langs.jar
fi

JAVA_RAM_KB=652700
echo "Running tests..."

export JVM_OPTIONS="-Xms${JAVA_RAM_KB}K -Xmx${JAVA_RAM_KB}K ${runtime_params[@]}"
export LC_ALL=C.UTF-8
java -XX:+TieredCompilation -XX:TieredStopAtLevel=1 -jar tmc-langs.jar run-tests --exercisePath . --outputPath /app/test_output.txt --checkstyleOutputPath /app/validations.json --locale $error_msg_locale > >(tee -a stdout.log) 2> >(tee -a stderr.log >&2) || exit 104

echo "All the files:"
ls -laR
echo "tmc-run completed successfully"

exit 0
